version: '2'
        services:
          web:
            build: .
            command: php -S 0.0.0.0:$PORT -t /app/web/
            ports:
              - "8000:8000"
            volumes:
              - .:/app
            environment:
              PORT: 8000
